-- AlterEnum
ALTER TYPE "Role" ADD VALUE 'CREATOR';
ALTER TYPE "Role" ADD VALUE 'RESEARCHER'; 
ALTER TYPE "Role" ADD VALUE 'COMMUNITY';
ALTER TYPE "Role" ADD VALUE 'EDUCATOR';
ALTER TYPE "Role" ADD VALUE 'EXPERIMENTAL';

-- AlterTable - Change Agent.role from TEXT to Role enum
ALTER TABLE "Agent" ALTER COLUMN "role" SET DEFAULT 'GUEST';
ALTER TABLE "Agent" ALTER COLUMN "role" TYPE "Role" USING "role"::"Role";